<?php

namespace ContainerRziv4xj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DbGHAmeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DbGHAme' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DbGHAme'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'haieRepository' => ['privates', 'App\\Repository\\HaieRepository', 'getHaieRepositoryService', true],
        ], [
            'haieRepository' => 'App\\Repository\\HaieRepository',
        ]);
    }
}
