<?php

namespace ContainerRziv4xj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dy6AT1kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dy6AT1k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dy6AT1k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.q48KU4Q', 'get_ServiceLocator_Q48KU4QService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.q48KU4Q', 'get_ServiceLocator_Q48KU4QService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.q48KU4Q', 'get_ServiceLocator_Q48KU4QService', true],
            'App\\Controller\\DController::delete' => ['privates', '.service_locator.mKTleBI', 'get_ServiceLocator_MKTleBIService', true],
            'App\\Controller\\DController::edit' => ['privates', '.service_locator.mKTleBI', 'get_ServiceLocator_MKTleBIService', true],
            'App\\Controller\\DController::show' => ['privates', '.service_locator.mKTleBI', 'get_ServiceLocator_MKTleBIService', true],
            'App\\Controller\\HaieController::delete' => ['privates', '.service_locator.xfp4lm0', 'get_ServiceLocator_Xfp4lm0Service', true],
            'App\\Controller\\HaieController::edit' => ['privates', '.service_locator.xfp4lm0', 'get_ServiceLocator_Xfp4lm0Service', true],
            'App\\Controller\\HaieController::index' => ['privates', '.service_locator.DbGHAme', 'get_ServiceLocator_DbGHAmeService', true],
            'App\\Controller\\HaieController::show' => ['privates', '.service_locator.xfp4lm0', 'get_ServiceLocator_Xfp4lm0Service', true],
            'App\\Controller\\MesureController::index' => ['privates', '.service_locator.DbGHAme', 'get_ServiceLocator_DbGHAmeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.q48KU4Q', 'get_ServiceLocator_Q48KU4QService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.q48KU4Q', 'get_ServiceLocator_Q48KU4QService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.q48KU4Q', 'get_ServiceLocator_Q48KU4QService', true],
            'App\\Controller\\DController:delete' => ['privates', '.service_locator.mKTleBI', 'get_ServiceLocator_MKTleBIService', true],
            'App\\Controller\\DController:edit' => ['privates', '.service_locator.mKTleBI', 'get_ServiceLocator_MKTleBIService', true],
            'App\\Controller\\DController:show' => ['privates', '.service_locator.mKTleBI', 'get_ServiceLocator_MKTleBIService', true],
            'App\\Controller\\HaieController:delete' => ['privates', '.service_locator.xfp4lm0', 'get_ServiceLocator_Xfp4lm0Service', true],
            'App\\Controller\\HaieController:edit' => ['privates', '.service_locator.xfp4lm0', 'get_ServiceLocator_Xfp4lm0Service', true],
            'App\\Controller\\HaieController:index' => ['privates', '.service_locator.DbGHAme', 'get_ServiceLocator_DbGHAmeService', true],
            'App\\Controller\\HaieController:show' => ['privates', '.service_locator.xfp4lm0', 'get_ServiceLocator_Xfp4lm0Service', true],
            'App\\Controller\\MesureController:index' => ['privates', '.service_locator.DbGHAme', 'get_ServiceLocator_DbGHAmeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ClientController::delete' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\DController::delete' => '?',
            'App\\Controller\\DController::edit' => '?',
            'App\\Controller\\DController::show' => '?',
            'App\\Controller\\HaieController::delete' => '?',
            'App\\Controller\\HaieController::edit' => '?',
            'App\\Controller\\HaieController::index' => '?',
            'App\\Controller\\HaieController::show' => '?',
            'App\\Controller\\MesureController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ClientController:delete' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\DController:delete' => '?',
            'App\\Controller\\DController:edit' => '?',
            'App\\Controller\\DController:show' => '?',
            'App\\Controller\\HaieController:delete' => '?',
            'App\\Controller\\HaieController:edit' => '?',
            'App\\Controller\\HaieController:index' => '?',
            'App\\Controller\\HaieController:show' => '?',
            'App\\Controller\\MesureController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
