<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQkyFrbb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQkyFrbb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQkyFrbb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQkyFrbb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQkyFrbb\App_KernelDevDebugContainer([
    'container.build_hash' => 'QkyFrbb',
    'container.build_id' => '12b124cf',
    'container.build_time' => 1644313234,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQkyFrbb');
