<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNngBRwx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNngBRwx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNngBRwx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNngBRwx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNngBRwx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NngBRwx',
    'container.build_id' => 'ba86dee8',
    'container.build_time' => 1646982751,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNngBRwx');
